version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.6
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements-dev.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements-dev.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements-dev.txt" }}
          paths:
            - "venv"
      - run:
          name: Lint
          command: make lint
      - run:
          name: Run tests
          command: make test